services:
  - type: web
    name: meta-report-service
    runtime: python
    python:
      version: 3.11.0
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: META_API_KEY
        sync: false
      - key: META_AD_ACCOUNT_ID
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_RECIPIENTS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: REPORT_TYPE
        sync: false
      - key: ENV
        sync: false
    healthCheckPath: /health
    autoDeploy: true
